version: '3.4'

services:
  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: src/Services/NotificationService/NotificationService/Dockerfile

  identitydb:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
  rabbitmq:
     image: rabbitmq:3-management



volumes:
  identitydb_volume:


