version: '3.4'

services:
  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile
  db:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
  rabbitmq:
     image: rabbitmq:3-management
volumes:
  mymssqldb_volume:
