version: '3.4'

services:

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433; 
          Database=IdentityDb; User=sa; Password=SwN12345678;"
    ports:
      - "80"
      - "443"
      - "44378:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - identitydb_volume:/var/opt/mssql/data

    depends_on:
      - rabbitmq
      - identitydb


  identitydb:
    container_name: identitydb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"


  rabbitmq:
    container_name: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"


        
     
        
            